Fix CI (#2767)
* fix typos

* fix AttributeError: 'range' object has no attribute 'remove' in dev_scripts/chemenv/equivalent_indices.py

* add missing doc strings in dev_scripts/chemenv/strategies/multi_weights_strategy_parameters.py

* fix TypeError: Object of type ndarray is not JSON serializable

in         with open("tmp_dir/lse.json", "w") as f:
>           json.dump(lse.as_dict(), f)

pymatgen/analysis/chemenv/coordination_environments/tests/test_read_write.py:81: