Python 3.14 support (#4516)
* remove pdm dev-dependency section in pyproject (likely not needed?)

https://github.com/materialsproject/pymatgen/commit/fb6ba71dac3cf6a079aaa2b85c0e4971434ba1ad

* clean up tool.coverage exclude section

remove self explanatory comment

* skip netcdf4 test in Linux CI >=1.6.5, clean up tests

xfail for netcdf4 in ubuntu CI

* test and build Python 3.14 wheels

fail back to 3.13 for lint as pyright is not installable

revert win to 3.11 for now (cannot recreate locally)

resolve to highest in Ubuntu

fix different err msg in 3.14

➜  temp uv run -p 3.13 test_index.py
Traceback (most recent call last):
  File "/Users/yang/developer/temp/test_index.py", line 1, in <module>
    print(["a"].index(1))
          ~~~~~~~~~~~^^^
ValueError: 1 is not in list

➜  temp uv run -p 3.14 test_index.py
Traceback (most recent call last):
  File "/Users/yang/developer/temp/test_index.py", line 1, in <module>
    print(["a"].index(1))
          ~~~~~~~~~~~^^^
ValueError: list.index(x): x not in list

skip netcdf4 in 3.13

skip more py 3.14 incompatible deps

matcalc seems installable on python 3.13 and 3.14

skip more packages that doesn't support 3.14 now

remove pin for pure python analysis-alloy

remove comment

drop openai pin

unblock h5py

unpin netcdf4

---------

Co-authored-by: Matt Horton <mkhorton@users.noreply.github.com>